### PR TITLE
Skip newlines in binary decoding (Fix #387)

### LINKED ISSUE #387: does not support generic format binary encoding
I'm on master 728e26e42645d4d70ca65522990f915f47b47a50
I copied the example binary data from [from the spec](http://yaml.org/type/binary.html)

```
canonical: !!binary "\
 R0lGODlhDAAMAIQAAP//9/X17unp5WZmZgAAAOfn515eXvPz7Y6OjuDg4J+fn5\
 OTk6enp56enmlpaWNjY6Ojo4SEhP/++f/++f/++f/++f/++f/++f/++f/++f/+\
 +f/++f/++f/++f/++f/++SH+Dk1hZGUgd2l0aCBHSU1QACwAAAAADAAMAAAFLC\
 AgjoEwnuNAFOhpEMTRiggcz4BNJHrv/zCFcLiwMWYNG84BwwEeECcgggoBADs="
generic: !binary |
 R0lGODlhDAAMAIQAAP//9/X17unp5WZmZgAAAOfn515eXvPz7Y6OjuDg4J+fn5
 OTk6enp56enmlpaWNjY6Ojo4SEhP/++f/++f/++f/++f/++f/++f/++f/++f/+
 +f/++f/++f/++f/++f/++SH+Dk1hZGUgd2l0aCBHSU1QACwAAAAADAAMAAAFLC
 AgjoEwnuNAFOhpEMTRiggcz4BNJHrv/zCFcLiwMWYNG84BwwEeECcgggoBADs=
description:
 The binary value above is a tiny arrow encoded as a gif image.
```

And am trying to read that with this little test application:

```
#include <yaml-cpp/yaml.h>
#include <iostream>

using std::cout;
using std::endl;

int main(int argc, char * argv[]) {
  YAML::Node in = YAML::LoadFile(argv[1]);
  if (!in["canonical"])
    throw std::runtime_error("canonical field");
  if (!in["generic"])
    throw std::runtime_error("generic field");

  YAML::Binary canonical, generic;
  try {
    canonical = in["canonical"].as<YAML::Binary>();
  } catch (const YAML::Exception& e) {
    cout << "error reading canonical " << e.what() << endl;
    exit(0);
  }
  try {
    generic = in["generic"].as<YAML::Binary>();
  } catch (const YAML::Exception& e) {
    cout << "error reading generic " << e.what() << endl;
    exit(0);
  }

  return 0;
}
```

`clang++ -g main.cpp -o bintest -l yaml-cpp`
`./bintest example.yaml`

gives me an exception reading in the generic data.

I've attached both the code and yaml file as a zip:

[code-and-yaml.zip](https://github.com/jbeder/yaml-cpp/files/309429/code-and-yaml.zip)

### PR DESCRIPTION
**Pull request by ithron**
This fixes #387

### CODE REVIEW

File: src/binary.cpp [hunk 1]
```diff
@@ -72,19 +74,21 @@ std::vector<unsigned char> DecodeBase64(const std::string &input) {
   unsigned char *out = &ret[0];
 
   unsigned value = 0;
-  for (std::size_t i = 0; i < input.size(); i++) {
+  for (std::size_t i = 0, cnt = 0; i < input.size(); i++) {
+    if (isspace(input[i])) continue; // skip newlines
```
Comment (jbeder) [inline src/binary.cpp]: Add braces, even to this one-line "if" statement; and then put the "continue" on its own line

Comment (jbeder) [inline src/binary.cpp]: Fully-qualify std::isspace.
