### PR TITLE
fix issue501: handle the long key properly.

### LINKED ISSUE #501: Long key not handled properly
This should work, but does not:

int main(void)
{
    YAML::Node nn;
    nn[std::string(2000, 'a')] = 0;
    YAML::Load(YAML::Dump(nn));
    return 0;
}

--> Terminate called after throwing an instance of 'YAML::ParserException'
  what():  yaml-cpp: error at line 1, column 2001: illegal map value

I believe the problem is that the long key should be emitted as such:

? LONGKEY
: value

### PR DESCRIPTION
**Pull request by dota17**
fix #501 
write the long key (> 1024) properly.

### CODE REVIEW

File: test/integration/emitter_test.cpp [hunk 1]
```diff
@@ -266,16 +266,23 @@ TEST_F(EmitterTest, SimpleLongKey) {
 }
 
 TEST_F(EmitterTest, SingleLongKey) {
+  const std::string& shortKey = std::string(1024, 'a');
```
Comment (jbeder) [inline test/integration/emitter_test.cpp:269]: 1) it’s more idiomatic to have this be a value, not a reference
2) you can construct it directly (rather than use =)

Comment (dota17) [reply test/integration/emitter_test.cpp]: ok, I have modified it.
